### ISSUE TITLE
Is it only a counry?

### ISSUE THREAD

**Issue by mmm25002500** [Cvar1984/LiteOTP#1]
Is it only a country,it can't send to Taiwan,China,Japan. 
I don't know how can it change country.

**Comment by Cvar1984** [comment]
Yes, for now its only for one country (_indonesia_)
I will do some small _otp api_ research for the next update

**Comment by myfacefx** [comment]
ini masi jalan bro?

**Comment by Cvar1984** [comment]
Cek versi [2.0.8](https://github.com/Cvar1984/LiteOTP/releases/tag/2.0.8)
