### ISSUE TITLE
Letak file

### ISSUE THREAD

**Issue by daptheHuman** [Cvar1984/LiteOTP#5]
Kalo untuk masal file defaultny dimana?

**Comment by Cvar1984** [comment]
terimaksaih sudah bertanya, sudah baca README.md?
untuk masal bisa buat file ber isi list nomor telephone nya, contoh
```
88802019456
85702018825
88802024467
22202019462
85802019466
```
lalu simpan dengan nama bebas atau list.txt
lalu exsekusi dengan command contoh $ lite /home/list.txt

ingat, untuk memasukan nama file harus disertai full path untuk php versi terbaru.
